#!/usr/bin/env python

import argparse, getpass, httplib, os

PYBOT_CMDLINE = "pybot --variable USER:%s --variable PASSWORD:%s --variable URL:%s --loglevel TRACE src/test.robot"
SUBMARINO_URL = "https://www.submarino.com.br"

def isSeleniumRunning():

    # try to connect to selenium server
    conn = httplib.HTTPConnection("localhost:4444")
    conn.request("HEAD", "/wd")
    res = conn.getresponse()

    # if available return true, false otherwise
    if res.status == 200:
        return True
    return False

def runTests(user, password, url):
    os.system(PYBOT_CMDLINE % (user, password, url))

def main():
    parser = argparse.ArgumentParser()

    # script will receive --user and --url as parameter
    parser.add_argument("user", help="User of Submarino's e-commerce. If present, password will be prompted")
    parser.add_argument("url", help="URL to e-commerce. Supported URLs: %s" % SUBMARINO_URL)
    args = parser.parse_args()

    # validate url
    if args.url != SUBMARINO_URL:
        print "The following %s is not supported by this automated tests" % args.url
        return 1

    # prompt password
    #password = getpass.getpass()
    password = "desafiocit"
    runTests(args.user, password, args.url)

main()

